language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - cd udagram-api-feed && npm install && cd ..
  - cd udagram-api-user && npm install && cd ..
  - cd udagram-reverseproxy && npm install && cd ..
  - cd udagram-frontend && npm install && cd ..

# Scripts to be run such as tests
before_script:
  - echo "no tests allowed"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed madhaviag/udagram-api-feed:v10
  - docker tag udagram-api-user madhaviag/udagram-api-user:v10
  - docker tag udagram-frontend madhaviag/udagram-frontend:v10
  - docker tag reverseproxy madhaviag/reverseproxy:v10


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push madhaviag/udagram-api-feed:v10
  - docker push madhaviag/udagram-api-user:v10
  - docker push madhaviag/udagram-frontend:v10
  - docker push madhaviag/reverseproxy:v10
  